version: '3.8'

services:
  mongodb:
    image: mongo:8.0.4
    container_name: mongodb
    ports:
      - "27007:27017"
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - backend
    restart: always

  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.29.0
    container_name: weaviate
    ports:
      - "8080:8080"   # منفذ HTTP
      - "50051:50051" # منفذ GRPC
    volumes:
      - weaviate_data:/var/lib/weaviate
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=none
      - ENABLE_MODULES=text2vec-openai
      - CLUSTER_HOSTNAME=node1
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:

volumes:
  mongodb:
  weaviate_data:
